#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("SwipeListViewSample.Resource", IsApplication=true)]

namespace SwipeListViewSample
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010008
			public const int swipeActionLeft = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int swipeActionRight = 2130771977;
			
			// aapt resource value: 0x7f010001
			public const int swipeAnimationTime = 2130771969;
			
			// aapt resource value: 0x7f010006
			public const int swipeBackView = 2130771974;
			
			// aapt resource value: 0x7f010004
			public const int swipeCloseAllItemsWhenMoveList = 2130771972;
			
			// aapt resource value: 0x7f01000a
			public const int swipeDrawableChecked = 2130771978;
			
			// aapt resource value: 0x7f01000b
			public const int swipeDrawableUnchecked = 2130771979;
			
			// aapt resource value: 0x7f010005
			public const int swipeFrontView = 2130771973;
			
			// aapt resource value: 0x7f010007
			public const int swipeMode = 2130771975;
			
			// aapt resource value: 0x7f010002
			public const int swipeOffsetLeft = 2130771970;
			
			// aapt resource value: 0x7f010003
			public const int swipeOffsetRight = 2130771971;
			
			// aapt resource value: 0x7f010000
			public const int swipeOpenOnLongPress = 2130771968;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int background_app = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int background_list_back = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int background_list_front = 2130968578;
			
			// aapt resource value: 0x7f040006
			public const int background_new_tag = 2130968582;
			
			// aapt resource value: 0x7f040005
			public const int line = 2130968581;
			
			// aapt resource value: 0x7f040004
			public const int text_description = 2130968580;
			
			// aapt resource value: 0x7f040007
			public const int text_new_tag = 2130968583;
			
			// aapt resource value: 0x7f040003
			public const int text_title = 2130968579;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050007
			public const int font_size_description = 2131034119;
			
			// aapt resource value: 0x7f050009
			public const int font_size_new_tag = 2131034121;
			
			// aapt resource value: 0x7f050006
			public const int font_size_title = 2131034118;
			
			// aapt resource value: 0x7f050004
			public const int height_list = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int line_default = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int margin_default = 2131034114;
			
			// aapt resource value: 0x7f050008
			public const int margin_setting = 2131034120;
			
			// aapt resource value: 0x7f050001
			public const int padding_default = 2131034113;
			
			// aapt resource value: 0x7f05000a
			public const int padding_new_tag = 2131034122;
			
			// aapt resource value: 0x7f050000
			public const int radius_default = 2131034112;
			
			// aapt resource value: 0x7f050005
			public const int size_list_image = 2131034117;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int background_item = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int background_new_tag = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int choice_selected = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int choice_unselected = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Icon = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080009
			public const int back = 2131230729;
			
			// aapt resource value: 0x7f080000
			public const int both = 2131230720;
			
			// aapt resource value: 0x7f080004
			public const int choice = 2131230724;
			
			// aapt resource value: 0x7f080005
			public const int dismiss = 2131230725;
			
			// aapt resource value: 0x7f080007
			public const int example_lv_list = 2131230727;
			
			// aapt resource value: 0x7f08000a
			public const int example_row_b_action_3 = 2131230730;
			
			// aapt resource value: 0x7f08000b
			public const int example_row_iv_image = 2131230731;
			
			// aapt resource value: 0x7f08000c
			public const int example_row_tv_title = 2131230732;
			
			// aapt resource value: 0x7f080008
			public const int front = 2131230728;
			
			// aapt resource value: 0x7f080001
			public const int left = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int none = 2131230722;
			
			// aapt resource value: 0x7f080006
			public const int reveal = 2131230726;
			
			// aapt resource value: 0x7f080003
			public const int right = 2131230723;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int package_row = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060018
			public const int about = 2131099672;
			
			// aapt resource value: 0x7f060019
			public const int aboutMessage = 2131099673;
			
			// aapt resource value: 0x7f060015
			public const int animationTime = 2131099669;
			
			// aapt resource value: 0x7f060003
			public const int appName = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int app_name = 2131099650;
			
			// aapt resource value: 0x7f06000c
			public const int both = 2131099660;
			
			// aapt resource value: 0x7f060007
			public const int cantOpen = 2131099655;
			
			// aapt resource value: 0x7f060010
			public const int choice = 2131099664;
			
			// aapt resource value: 0x7f060021
			public const int discard = 2131099681;
			
			// aapt resource value: 0x7f06000f
			public const int dismiss = 2131099663;
			
			// aapt resource value: 0x7f06001d
			public const int dontShow = 2131099677;
			
			// aapt resource value: 0x7f060014
			public const int dp = 2131099668;
			
			// aapt resource value: 0x7f06001c
			public const int goToGitHub = 2131099676;
			
			// aapt resource value: 0x7f060005
			public const int googlePlay = 2131099653;
			
			// aapt resource value: 0x7f060001
			public const int hello = 2131099649;
			
			// aapt resource value: 0x7f06000a
			public const int left = 2131099658;
			
			// aapt resource value: 0x7f06000d
			public const int leftAction = 2131099661;
			
			// aapt resource value: 0x7f060013
			public const int leftOffset = 2131099667;
			
			// aapt resource value: 0x7f06001f
			public const int loading = 2131099679;
			
			// aapt resource value: 0x7f060016
			public const int milliseconds = 2131099670;
			
			// aapt resource value: 0x7f060009
			public const int mode = 2131099657;
			
			// aapt resource value: 0x7f060020
			public const int newTag = 2131099680;
			
			// aapt resource value: 0x7f06001a
			public const int ok = 2131099674;
			
			// aapt resource value: 0x7f060004
			public const int open = 2131099652;
			
			// aapt resource value: 0x7f060017
			public const int openOnLongPress = 2131099671;
			
			// aapt resource value: 0x7f06001e
			public const int others = 2131099678;
			
			// aapt resource value: 0x7f06000e
			public const int reveal = 2131099662;
			
			// aapt resource value: 0x7f06000b
			public const int right = 2131099659;
			
			// aapt resource value: 0x7f060011
			public const int rightAction = 2131099665;
			
			// aapt resource value: 0x7f060012
			public const int rightOffset = 2131099666;
			
			// aapt resource value: 0x7f060008
			public const int settings = 2131099656;
			
			// aapt resource value: 0x7f060000
			public const int swipeRevealDismissThreshold = 2131099648;
			
			// aapt resource value: 0x7f060006
			public const int uninstall = 2131099654;
			
			// aapt resource value: 0x7f06001b
			public const int visit47 = 2131099675;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070009
			public const int Line = 2131165193;
			
			// aapt resource value: 0x7f070000
			public const int ListBackContent = 2131165184;
			
			// aapt resource value: 0x7f070005
			public const int ListButtonAction = 2131165189;
			
			// aapt resource value: 0x7f070004
			public const int ListDescription = 2131165188;
			
			// aapt resource value: 0x7f070001
			public const int ListFrontContent = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int ListImage = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int ListTitle = 2131165187;
			
			// aapt resource value: 0x7f07000a
			public const int New = 2131165194;
			
			// aapt resource value: 0x7f070007
			public const int SettingContent = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int SettingText = 2131165192;
			
			// aapt resource value: 0x7f070006
			public const int SettingTitle = 2131165190;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] SwipeListView = new int[]
			{
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979};
			
			// aapt resource value: 8
			public const int SwipeListView_swipeActionLeft = 8;
			
			// aapt resource value: 9
			public const int SwipeListView_swipeActionRight = 9;
			
			// aapt resource value: 1
			public const int SwipeListView_swipeAnimationTime = 1;
			
			// aapt resource value: 6
			public const int SwipeListView_swipeBackView = 6;
			
			// aapt resource value: 4
			public const int SwipeListView_swipeCloseAllItemsWhenMoveList = 4;
			
			// aapt resource value: 10
			public const int SwipeListView_swipeDrawableChecked = 10;
			
			// aapt resource value: 11
			public const int SwipeListView_swipeDrawableUnchecked = 11;
			
			// aapt resource value: 5
			public const int SwipeListView_swipeFrontView = 5;
			
			// aapt resource value: 7
			public const int SwipeListView_swipeMode = 7;
			
			// aapt resource value: 2
			public const int SwipeListView_swipeOffsetLeft = 2;
			
			// aapt resource value: 3
			public const int SwipeListView_swipeOffsetRight = 3;
			
			// aapt resource value: 0
			public const int SwipeListView_swipeOpenOnLongPress = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
